node: https://rpc.cudos.org:443
chain-id: cudos-1
# defines the scheduling interval that withdraw-rewards will be executed
interval: 60s
# path to keyring-dir of cudos-node in order to access keys stored for the test backend
keyring-dir: /Users/yuliyan/cudos-node/cudos-data
