// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ShutdownReady is an autogenerated mock type for the ShutdownReady type
type ShutdownReady struct {
	mock.Mock
}

// SetReady provides a mock function with given fields: ready
func (_m *ShutdownReady) SetReady(ready bool) bool {
	ret := _m.Called(ready)

	if len(ret) == 0 {
		panic("no return value specified for SetReady")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(bool) bool); ok {
		r0 = rf(ready)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewShutdownReady creates a new instance of ShutdownReady. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShutdownReady(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShutdownReady {
	mock := &ShutdownReady{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
